### PR TITLE
Fix widget divider visibility

### LINKED ISSUE #2378: App draws unnecessary lines at the top of frames
### Actual behaviour
The App draws unnecessary and unwanted lines between items when they are not visible because of their config. 
Example: 

1. 
  ```
  Frame
    {
        Text item=Netzwerk_DLANStatus label="DLAN muss wiederhergestellt werden" visibility=[Netzwerk_DLANStatus==OFF]
        Text item=System_Updates_OpenHAB label="OpenHAB Update verfügbar" visibility=[System_Updates_OpenHAB!="OFF"]
        Text item=Android_Wecker_Formatiert visibility=[Android_Wecker_Gestellt==ON]
    }
```
The first Item is not visible since `Netzwerk_DLANStatus=OFF`.
Screenshot_20210124-151149
You can see a line and some spacing between the top of the page and "OpenHAB Update verfügbar". Moreover you can see the exact same problem at the beginning of the frame "Multimedia". Draw attention to the line at the beginning of the "Multimedia" frame and the missing line in the "Steckdosen" frame.

2. When I now comment out the first line the line disappears:
Screenshot_20210124-151210
These unwanted lines only appear at the top of a frame if the first item is not visible.

### Expected behaviour
The lines should not be visible

 
### Steps to reproduce
1. See config as above

#### Client
* Android version: 11 (just upgraded yesterday, was on 10 as well)
* Device model: OnePlus 7TPro HD1913
* App version : 2.15.15-beta
* Build flavor : Full
* Device language: German

#### Server
* Server version: 2.5-10 (happens on 2.5-11 as well)
* Reverse Proxy: No
* Important Parts of the sitemap: 
[sitemap.txt](https://github.com/openhab/openhab-android/files/5862429/sitemap.txt)

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #2378

@Trysupe I tested all your sitemap examples from #2378 and it looks good now, but maybe you can also test it:

[mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/7148593/mobile-foss-beta-debug.zip)

- Rename it to .apk
- Uninstall openHAB Beta if installed
- Install my apk

### CODE REVIEW

**Comment by maniac103** [comment]
Simplification suggestion on top of your patch:

```diff
diff --git a/mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt b/mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
index d2e01afd..7daf6c53 100644
--- a/mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
+++ b/mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
@@ -1391,32 +1391,13 @@ class WidgetAdapter(
                 return false
             }
 
-            val adapter = parent.adapter
-            val viewTypeCurrentPos = adapter?.getItemViewType(position) ?: return false
-
-            return when {
-                // Hide divider after frame widgets and invisible ones
-                viewTypeCurrentPos in NO_DIVIDER_TYPES -> true
-                // Hide divider if it's the last visible widget
-                isLastVisibleWidget(position, adapter) -> true
-                else -> false
-            }
-        }
-
-        private fun isLastVisibleWidget(position: Int, adapter: RecyclerView.Adapter<RecyclerView.ViewHolder>):
-            Boolean {
-                var positionToCheck = position + 1
+            val adapter = parent.adapter ?: return false
 
-                while (positionToCheck < adapter.itemCount) {
-                    val viewType = adapter.getItemViewType(positionToCheck)
-                    if (viewType !in NO_DIVIDER_TYPES) {
-                        return false
-                    }
-                    positionToCheck++
-                }
-
-                return true
-            }
+            // Hide divider if this and all following positions shouldn't have dividers
+            return (position until adapter.itemCount)
+                .map { pos -> adapter.getItemViewType(pos) }
+                .all { type -> type in NO_DIVIDER_TYPES }
+        }
 
         companion object {
             private val NO_DIVIDER_TYPES = intArrayOf(TYPE_FRAME, TYPE_INVISIBLE)
```

AFAICT it should do exactly the same thing.

**Comment by mueller-ma** [comment]
Your patch doesn't work for me in several cases, e.g.: When the last item is invisible there's still a divider shown at the end.

**Comment by maniac103** [comment]
I'll check it, it's probably just a matter of range bounds. Would you agree that your patch essentially does 'hide dividers if current or any following position is in NO_DIVIDER_TYPES', though? AFAICT, the former is done by the first part of the when statement, and the latter is done by the `isLastVisibleWidget` method.

**Comment by mueller-ma** [comment]
> 'hide dividers if current or any following position is in NO_DIVIDER_TYPES'

Correct. But in your patch the

**Comment by maniac103** [comment]
> Your patch doesn't work for me in several cases

Fixed: https://github.com/maniac103/openhab.android/commit/b026ea4f5618270e52e1ba21ffb324afcad8541d ... previous patch did 'hide if current *and* all following positions are in NO_DIVIDER_TYPES', while it should be 'hide if current *or* all following...'.

**Comment by Trysupe** [comment]
> @Trysupe I tested all your sitemap examples from #2378 and it looks good now, but maybe you can also test it:

Hey there, I am sorry I was only able to test this now since the last few days have been pretty stressful at work...
I tested the new version and it now displays the missing line but also draws one too much. See this example:



This is the openHAB Stable App on the bottom and your beta version on top divided by the blue line in the missle

You can see 
- the missing line on top of the element `Asterix` in the frame `Multimedia` is now there 👍🏻 
- However it also draws (imo.) unnecessary lines at the end of frames as you can see at the end of the top frame and the one named `Steckdosen`

----

<details><summary>This is the code for the shown section</summary>
<p>

```
Frame label="Licht"
{
    [...]

    Slider item=Licht_Bettlampe visibility=[Netzwerk_Bettlampe_Online==ON]
    Text item=Netzwerk_Bettlampe_OfflineSeit label="Bettlampe offline seit" labelcolor=["red"] valuecolor=["red"] visibility=[Netzwerk_Bettlampe_Online==OFF]
    Switch item=Steckdosen_Bettlampe label="Power" mappings=["0.0"="AUS", "1.0"="REBOOT", "2.0"="AN"] visibility=[Netzwerk_Bettlampe_Online==OFF]

    Switch item=Licht_Lichterkette_Status mappings=[OFF="AUS", ON="AN"] visibility=[Netzwerk_HarmonyHub_Online==ON]

    Text label="Nanoleaf & Andere" icon=lightbulb
    {
        [...]
    }
}

Frame label="Steckdosen" visibility=[Netzwerk_BrennstuhlBridge_Online==ON]
{
    Switch item=Steckdosen_Heizdecke mappings=["0.0"="AUS", "1.0"="NEU", "2.0"="AN"]
    Text item=Steckdosen_Heizdecke_AnUndAusschaltzeit visibility=[Steckdosen_Heizdecke != "0.0"]
    Text label="Alle" icon="switch"
    {
        [...]
    }
}
Frame label="Steckdosen" visibility=[Netzwerk_BrennstuhlBridge_Online==OFF]
{
    Text item=Netzwerk_BrennstuhlBridge_OfflineSeit label="Brennstuhl Bridge offline seit" labelcolor=["red"] valuecolor=["red"]
}

Frame label="Multimedia" visibility=[Netzwerk_HarmonyHub_Online==ON]
{
    Switch item=Multimedia_Aktuell label="" mappings=["Fernseher"="Fernseher", "PC"="PC", "PC auf Fernseher"="PC auf Fernseher"] visibility=[Multimedia_Aktuell=="Aus"]
    Switch item=Multimedia_Aktuell label="" mappings=["Fernseher"="Fernseher", "PC"="PC", Aus="Aus"] visibility=[Multimedia_Aktuell=="PC auf Fernseher"]
    Switch item=Multimedia_Aktuell label="" mappings=["Fernseher"="Fernseher", "PC auf Fernseher"="PC auf Fernseher", Aus="Aus"] visibility=[Multimedia_Aktuell=="PC"]
    Switch item=Multimedia_Aktuell label="" mappings=["PC"="PC", "PC auf Fernseher"="PC auf Fernseher", Aus="Aus"] visibility=[Multimedia_Aktuell=="Fernseher"]
    Switch item=Multimedia_FireTV mappings=[HOME="Home", PAUSE="Play"]visibility=[Multimedia_Aktuell=="Fernseher"]
    Switch item=PC_Asterix_Power label="Asterix" mappings=[OFF="AUS", ON="AN"] visibility=[Multimedia_Aktuell=="Aus", Multimedia_Aktuell=="PC"]
    [...]
}
```
</p>
</details>

**Comment by mueller-ma** [comment]
Thanks for this report. I used the light theme to test this and there the divider at the end of a frame hardly visible.

**Comment by Trysupe** [comment]
> I used the light theme to test this and there the divider at the end of a frame hardly visible.

Okay makes sense that you see it then. Shall I test something else as well?

**Comment by mueller-ma** [comment]
> hide dividers if current or any following position is in NO_DIVIDER_TYPES

It should be "hide dividers if current is in NO_DIVIDER_TYPES or any following position in the current frame is invisible": https://github.com/openhab/openhab-android/pull/2702/commits/982f442326f7c4f08f3d8059d0503f3baca07a06

**Comment by Trysupe** [comment]
Can you build a new package that I can try and give you feedback upon?

**Comment by mueller-ma** [comment]
Sure: [mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/7180626/mobile-foss-beta-debug.zip)

**Comment by Trysupe** [comment]
> Sure: [mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/7180626/mobile-foss-beta-debug.zip)

That's it! That's just how it it supposed to look. Save it and don't change a thing 😝

**Pull request merged**
