### PR TITLE
Work around appcompat forcing font scale to 1.0

### LINKED ISSUE #1613: Font size too small with high-res tablet since version 2.9
After updating to version 2.9, I discovered that the font size is very small on my old but very high-res tablet (Google Nexus 10).
On my very recent smartphone, the font size is normal.
Is it possible to restore a bigger font for high-res tablet ? Or to add a setting to select the font size ?

### PR DESCRIPTION
**Pull request by maniac103**
Fixes #1613

### CODE REVIEW

**Comment by maniac103** [comment]
This commit can be reverted after updating appcompat to a version which includes https://android.googlesource.com/platform/frameworks/support/+/1795e4ebdd262598f3c90b79cd3d75d79a5a2264

**Comment by lolodomo** [comment]
I am available in case you need my help to test a pre-version.
By the way, thanks for analyzing an fixing my problem, I really appreciate.

**Comment by mueller-ma** [comment]
Can you please test the following apk?

- Rename it to .apk
- Uninstall openHAB Beta if installed
- Install my apk

[mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/3780262/mobile-foss-beta-debug.zip)

**Comment by lolodomo** [comment]
I can confirm that the bug is fixed. Bravo.

**Comment by lolodomo** [comment]
Please note that the settings and about pages are still in a smaller (unscalled ?) font size.

**Comment by maniac103** [comment]
Damn, should have put that in the activity base class. Will submit a new PR.

**Pull request merged**
