### PR TITLE
Update list selector

### PR DESCRIPTION
**Pull request by mueller-ma**
See #1938

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by maniac103** [comment]
Continuing from https://github.com/openhab/openhab-android/issues/1938#issuecomment-612355017 ... why not semi transparent colorSecondary? You invalidated the one concern about that by yourself ;-)

I can't find much guidance about list selection in Material Design docs, but [this page](https://material.io/design/interaction/selection.html#) uses secondary color + alpha, and the default theme uses secondary color as well...

**Comment by mueller-ma** [comment]
> Continuing from #1938 (comment) ... why not semi transparent colorSecondary?

I changed it to pink for the basic ui theme. In the orange theme it makes no difference and in the grey theme the secondary color is different in day and night mode. And having white text on a white background is quite hard to read.

**Comment by maniac103** [comment]
> And having white text on a white background is quite hard to read

Sure, text still needs to be legible ;-)

Did you miss the 12% opacity comment or deliberately choose not to use that value?

**Comment by mueller-ma** [comment]
> Did you miss the 12% opacity comment or deliberately choose not to use that value?

I missed your edit.
How do I calculate "12%"? `FF` is 100% => 255 * 0.12 = 30,6 => 12% ~ `1E`? Using `1E` as alpha produces colors that are too light IMO.

**Comment by maniac103** [comment]
Yeah, that calculation is correct. I'll play round with this.

**Comment by maniac103** [comment]
I think I agree that 12% is way too low. Let's interpret the MD spec creatively and use the 36% opacity (`#5c...`) originally intended for image activation highlight ... that value seems to provide sufficient visibility to me, while still not being too stark.

BTW, your current selector drawable does not work for me on API 28 emulator. I needed this diff:
```diff
diff --git a/mobile/src/main/res/drawable/list_selector.xml b/mobile/src/main/res/drawable/list_selector.xml
index 7226eb81..1f71e190 100644
--- a/mobile/src/main/res/drawable/list_selector.xml
+++ b/mobile/src/main/res/drawable/list_selector.xml
@@ -1,6 +1,8 @@
 <?xml version="1.0" encoding="utf-8"?>
 <selector xmlns:android="http://schemas.android.com/apk/res/android">
-    <item android:state_activated="true" android:drawable="?attr/selectedWidgetBackgroundColor" />
+    <item android:state_activated="true">
+        <color android:color="?attr/selectedWidgetBackgroundColor" />
+    </item>
     <item>
         <ripple android:color="?attr/colorControlHighlight" />
     </item>
```

The problem probably is that `android:drawable` is only resolved as drawable, not as attribute.

**Comment by mueller-ma** [comment]
I picked your diff and updated the colors. RTM now.

**Pull request merged**
