### PR TITLE
Hide widgets from list when they become invisible.

### LINKED ISSUE #1392: Widgets do not disappear when Visibility changes to false
I have air conditioner controls set up in my sitemap. Visibility of controls depends on state of the master power Switch. After i set the switch to ON, dependent controls appear on the screen. But when i set the switch back to OFF, widgets show "nil" values but don't disappear from the display. I have to refresh the sitemap in order for them to disappear.
Demo mode doesn't seem to have any dynamic visibility settings, so can't reproduce in demo mode. The following is a fragment of my sitemap:
--- cut ---
Switch item=LRAC_Power label="Power"
Selection item=LRAC_Mode label="Mode" mappings=["AUTO"="Auto", "COLD"="Cooling", "HEAT"="Heating", "FAN"="Fan", "DEHUMIDIFIER"="Dryer"] visibility=[LRAC_Power==ON]
Setpoint item=LRAC_SetPoint label="Set temperature [%.1f °C]" visibility=[LRAC_Power==ON]
 --- cut ---

### PR DESCRIPTION
**Pull request by maniac103**
Stop-gap measure before full visibility handling (#1174)

Fixes #1392

### CODE REVIEW

**Comment by maniac103** [comment]
@Sonic-Amiga Could you please give this a try?

**Comment by maniac103** [comment]
@mueller-ma What are your plans regarding the next release? Before or after #1356? I have a few more fixes lying around, currently based on the Kotlin code, but if a release is going to happen before that, I can also rebase them for the Java code. I'd prefer to ship them post-Kotlin though, and if no release is going to happen before Kotlin, we can also postpone this one to be merged after #1356.

**Comment by mueller-ma** [comment]
I don't want to ship a release with #1371 not being fixed and I also have a few small fixes based on your Kotlin branch, so I'd say we wait for #1356 and than rebase every open PR.

**Comment by maniac103** [comment]
OK, good. We can postpone merging this one until post-Kotlin then.
(BTW, I have a fix for #1371 already: https://github.com/maniac103/openhab.android/commit/306f8107692749b1431aafe715a12e521a89fdcb)

**Comment by Sonic-Amiga** [comment]
Thank you, i will test it on this weekend.

**Comment by Sonic-Amiga** [comment]
@maniac103 Thank you very much; it works great.

**Comment by maniac103** [comment]
Thanks for testing this, I've included the fix in #1174.

**Pull request closed without merging**
