### PR TITLE
Use github teams instead of a list of users

### PR DESCRIPTION
**Pull request by mueller-ma**
See https://github.com/openhab/openhab-android/pull/593#issuecomment-354740254

### CODE REVIEW

**Comment by mueller-ma** [comment]
Can you sync the config?

**Comment by kaikreuzer** [comment]
No, it seems to have an error:
```
"{'ignored': True, 'auto': True}" is an invalid value for author_approval: only one of these settings can be true 
```

**Comment by mueller-ma** [comment]
Should be fixed: https://github.com/openhab/openhab-android/commit/e1ccd182de1ab520bd76d1f887e7e46c01d67199
I tested it in my fork and it sync successful.

**Comment by kaikreuzer** [comment]
Yes, that looks better - and it already sync'ed it automatically.

**Pull request merged**
