### PR TITLE
Fix race conditions in ConnectionFactory state updating.

### PR DESCRIPTION
**Pull request by maniac103**
Make sure the various dynamic state variables (available connection,
failure reason, cloud connection, init done tracking) are set
atomically.

### CODE REVIEW

**Comment by mueller-ma** [comment]
Build failed, but probably unrelated to this PR:

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Comment by mueller-ma** [comment]
Same failure reason again.

**Comment by maniac103** [comment]
Huh, I can't see tests failing, only the stalled build? What do you mean?

**Comment by mueller-ma** [comment]
Me neither, but something makes the build stall.

**Comment by maniac103** [comment]
Okay, now we have something to work with. I'll look into it.

**Comment by maniac103** [comment]
At least one aspect of the problem is that ConnectionFactoryTest updates the ConnectionFactory from its own thread instead of main thread. The initialization isn't thread safe though, just `waitForInitialization()` can be called from non-main threads. I'll update the test.

**Comment by maniac103** [comment]
I think I got it now.

**Pull request merged**
