### PR TITLE
Include item value in page title.

### LINKED ISSUE #1248: Value in page title is missing
### Actual behaviour
The title of any page is a fixed text defined in the sitemap as label.

### Expected behaviour
The title of any page should include, when defined in the sitemap, an additional (dynamic) value.
This is already correctly handled by Basic UI.

image

What I am talking about is the text "légère pluie" in the page title.

Example of sitemap to reproduce that:
```
Text item=OWMCondition label="Météo" icon="rain" {
}
```

Note that the value is already updated through SSE by the OH server.

### PR DESCRIPTION
**Pull request by maniac103**
Matches what BasicUI is doing.

Closes #1248

### CODE REVIEW

**Comment by maniac103** [comment]
Note: Mostly untested, as the server development environment currently seems completely broken for me (https://community.openhab.org/t/eclipse-automatic-build-runs-in-endless-loops/69545)

**Comment by mueller-ma** [comment]
The update doesn't work for me. I use http://demo.openhab.org:8080/basicui/app?w=020101&sitemap=demo for testing.

**Comment by maniac103** [comment]
Can you check your logcat for SSE failures? SSE towards the demo server seems to work only intermittently for me, with sometimes even BasicUI falling back to long polling.

**Comment by lolodomo** [comment]
If you need my help for testing, just provide an APK and I will tell you if it works or not.

**Comment by mueller-ma** [comment]
Log from local server with demo package:
````
03-10 18:28:37.356 org.openhab.habdroid.beta D/OkHttp: --> POST http://openhab/rest/items/Heating_GF_Kitchen
03-10 18:28:37.356 org.openhab.habdroid.beta D/OkHttp: Content-Type: text/plain;charset=UTF-8
03-10 18:28:37.356 org.openhab.habdroid.beta D/OkHttp: Content-Length: 2
03-10 18:28:37.356 org.openhab.habdroid.beta D/OkHttp: User-Agent: openHAB client for Android
03-10 18:28:37.356 org.openhab.habdroid.beta D/OkHttp: Authorization: ██
03-10 18:28:37.356 org.openhab.habdroid.beta D/OkHttp: Cache-Control: no-cache
03-10 18:28:37.356 org.openhab.habdroid.beta D/OkHttp: --> END POST
03-10 18:28:37.397 org.openhab.habdroid.beta D/OkHttp: <-- 200 OK http://openhab/rest/items/Heating_GF_Kitchen (40ms)
03-10 18:28:37.397 org.openhab.habdroid.beta D/OkHttp: Server: nginx/1.10.3
03-10 18:28:37.397 org.openhab.habdroid.beta D/OkHttp: Date: Sun, 10 Mar 2019 17:28:20 GMT
03-10 18:28:37.397 org.openhab.habdroid.beta D/OkHttp: Content-Type: text/plain
03-10 18:28:37.398 org.openhab.habdroid.beta D/OkHttp: Content-Length: 0
03-10 18:28:37.398 org.openhab.habdroid.beta D/OkHttp: Connection: keep-alive
03-10 18:28:37.399 org.openhab.habdroid.beta D/OkHttp: <-- END HTTP
03-10 18:28:37.418 org.openhab.habdroid.beta D/Util: Command 'ON' was sent successfully to http://openhab/rest/items/Heating_GF_Kitchen
03-10 18:28:37.582 org.openhab.habdroid.beta D/OkHttp: --> GET http://openhab/rest/sitemaps/events/67a98533-dc7b-4b20-a513-136417441032?sitemap=demo&pageid=demo
03-10 18:28:37.583 org.openhab.habdroid.beta D/OkHttp: User-Agent: openHAB client for Android
03-10 18:28:37.583 org.openhab.habdroid.beta D/OkHttp: Authorization: ██
03-10 18:28:37.584 org.openhab.habdroid.beta D/OkHttp: Accept-Encoding: 
03-10 18:28:37.585 org.openhab.habdroid.beta D/OkHttp: Accept: text/event-stream
03-10 18:28:37.585 org.openhab.habdroid.beta D/OkHttp: Cache-Control: no-cache
03-10 18:28:37.585 org.openhab.habdroid.beta D/OkHttp: --> END GET
03-10 18:28:37.611 org.openhab.habdroid.beta D/OkHttp: <-- 200 OK http://openhab/rest/sitemaps/events/67a98533-dc7b-4b20-a513-136417441032?sitemap=demo&pageid=demo (24ms)
03-10 18:28:37.611 org.openhab.habdroid.beta D/OkHttp: Server: nginx/1.10.3
03-10 18:28:37.611 org.openhab.habdroid.beta D/OkHttp: Date: Sun, 10 Mar 2019 17:28:20 GMT
03-10 18:28:37.612 org.openhab.habdroid.beta D/OkHttp: Content-Type: text/event-stream
03-10 18:28:37.612 org.openhab.habdroid.beta D/OkHttp: Transfer-Encoding: chunked
03-10 18:28:37.612 org.openhab.habdroid.beta D/OkHttp: Connection: keep-alive
03-10 18:28:37.612 org.openhab.habdroid.beta D/OkHttp: <-- END HTTP
````
Please note, that swipe-to-refresh also doesn't refresh the title.

**Comment by maniac103** [comment]
@mueller-ma Should be better now.

**Pull request merged**
