### PR TITLE
Fix status bar being invisible in chart and image activities

### PR DESCRIPTION
**Pull request by maniac103**
Do enableDrawingBehindStatusBar() unconditionally, as otherwise our app bar will be laid out on top of the status bar.

### CODE REVIEW

**Comment by mueller-ma** [comment]
I cannot reproduce this issue, but feel free to merge if it fixes it for you.

**Comment by maniac103** [comment]
Maybe I explained the issue poorly. Try opening a ChartActivity and check the status bar contents: are those visible for you? I used to only get a background, but no contents (clock, icons etc.) prior to this patch.

**Comment by mueller-ma** [comment]
> Try opening a ChartActivity and check the status bar contents: are those visible for you? 

Yes, it can see it correctly on [3.7.4-beta](https://github.com/openhab/openhab-android/releases/tag/3.7.4-beta).

**Comment by maniac103** [comment]
Just tried with exactly that version and got this:

Screenshot_20230917-153000_openHAB Beta

... so it definitely reproduces the issue. This sounds like an Android version thing then. What version does your device have? Android 13 here.

**Comment by maniac103** [comment]
Double checked the change doesn't break anything in Android 9 ... I think this should be safe to merge.

**Comment by SteWers** [comment]
The last beta works in Android 9 and 13.

**Pull request merged**
