### PR TITLE
Add /assets/store_descriptions/ to crowdin

### PR DESCRIPTION
**Pull request by mueller-ma**
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hmm doesn't seem to catch on. Let's wait another hour, otherwise @kaikreuzer needs to add this change through the crowdin frontend.

**Comment by mueller-ma** [comment]
@kaikreuzer

**Comment by kaikreuzer** [comment]
Err, what am I supposed to do...?

**Comment by mueller-ma** [comment]
Reload the crowdin config for this repo. This PR changed the config file, but the new string dont show up in crowdin

**Comment by kaikreuzer** [comment]
ok, should be in sync now.

**Pull request merged**
