### PR TITLE
Show local/remote connection only in debug mode

### PR DESCRIPTION
**Pull request by mueller-ma**
I don't see any use in these messages except for debugging, so show them only in debug mode.

### CODE REVIEW

**Comment by maniac103** [comment]
Personally I only have one use case: having a VPN connection active over a flaky mobile network. In that case the local server should be chosen, but due to the flaky mobile network it's sometimes not reachable. Maybe we should retry the connection check  in the background in that case.

**Comment by mueller-ma** [comment]
I don't understand your use case. How does the snackbar influence the connection?

**Comment by maniac103** [comment]
It doesn't, but it tells me the point in time where it's pointless to wait any longer for the content to load. I use myOH only for notifications, so the remote server won't give me contents either, this without the snack bar I won't be able to distinguish 'tries to establish local connection' from 'futile attempt to establish remote connection'.

**Comment by dilyanpalauzov** [comment]
In my environment I have an internal private IP address and public static IP address.  For some reason, probably because the provider wants so and I cannot adjust the router to do otherwise, I cannot access the external IP address from the internal network.  I find it useful to see whether OpenHAB-Android tries to connect to the internal or to the external network, and which one fails.

In fact I asked at https://github.com/openhab/openhab-android/issues/3417 to spell whether local or remote connection is retried after failure.

I think that “Restricting the local connections based on Wi-Fi name” shall be used as speedup - https://github.com/openhab/openhab-android/issues/3414 .  In this case I consider it good, if it is spelled explicitly whether the connection is made to local or remote server.

**Comment by mueller-ma** [comment]
What do you think about showing "Connecting to local/remote server" in the `ProgressFragment`?

**Comment by dilyanpalauzov** [comment]
As far as this question is for me, I do not know what the `ProgressFragment` is.

**Comment by mueller-ma** [comment]
> What do you think about showing "Connecting to local/remote server" in the ProgressFragment?

That's not possible any longer as the skeleton view is used while loading.

**Pull request closed without merging**
