### PR TITLE
Don't hide frames without label

### LINKED ISSUE #3160: Make nameless frames usefull for separation at sitemaps again
> This is the case, as I wrote: with nameless frames yo can separate with that shadow line. Now all my "separations" not shown any longer...

>That's understood and something we'll think about (and maybe worth opening a separate issue for, because it's actually actionable). Not sure yet what the best implementation for it with the 'flat' design is, maybe a thin orange line with a bit less padding around it?

_Originally posted by @maniac103 in https://github.com/openhab/openhab-android/issues/3159#issuecomment-1406305983_
 
Placed in a new issue like suggested.
The suggestion of a thin orange line would work perfect for me

### PR DESCRIPTION
**Pull request by mueller-ma**
Closes #3160

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by maniac103** [comment]
I assume the look of a frame with label is unchanged, right? Got a screenshot of a frame without label?

**Comment by mueller-ma** [comment]
The labeled frames didn't change. Here are two widgets divided by a frame without label.

grafik

**Comment by maniac103** [comment]
LGTM :+1: It's hidden if it's the first visible widget in a page, right?

**Comment by mueller-ma** [comment]
> It's hidden if it's the first visible widget in a page, right?

Correct

**Comment by mkrathome** [comment]
Thanks a lot 🖖🏻

**Pull request merged**
