### PR TITLE
Hide redundant value on switches

### PR DESCRIPTION
**Pull request by mueller-ma**
https://github.com/openhab/openhab-webui/pull/2579

### CODE REVIEW

**Comment by mueller-ma** [comment]
@lolodomo I'm using your setup from https://github.com/openhab/openhab-webui/pull/2579#issuecomment-2118788344.

How should the app know whether to show or hide the value on the two `Switch item=DemoNumber5 ...`? Here's the rest api for them:

````json
{
          "widgetId": "000101",
          "type": "Switch",
          "visibility": true,
          "label": "Switch no pattern [One]",
          "labelSource": "SITEMAP_WIDGET",
          "icon": "battery",
          "staticIcon": false,
          "pattern": "%.0f",
          "unit": "",
          "mappings": [],
          "item": {
            "link": "http://localhost:8080/rest/items/DemoNumber5",
            "state": "1",
            "stateDescription": {
              "pattern": "%.0f",
              "readOnly": false,
              "options": [
                {
                  "value": "0",
                  "label": "Zero"
                },
                {
                  "value": "1",
                  "label": "One"
                },
                {
                  "value": "2",
                  "label": "Two"
                }
              ]
            },
            "commandDescription": {
              "commandOptions": [
                {
                  "command": "0",
                  "label": "Zero"
                },
                {
                  "command": "1",
                  "label": "One"
                },
                {
                  "command": "2",
                  "label": "Two"
                }
              ]
            },
            "type": "Number",
            "name": "DemoNumber5",
            "label": "DemoNumber5",
            "category": "battery",
            "tags": [],
            "groupNames": [
              "DemoSwitchGroup"
            ]
          },
          "widgets": []
        },
        {
          "widgetId": "000102",
          "type": "Switch",
          "visibility": true,
          "label": "Switch _%s_ [_One_]",
          "labelSource": "SITEMAP_WIDGET",
          "icon": "battery",
          "staticIcon": false,
          "pattern": "_%s_",
          "unit": "",
          "mappings": [],
          "item": {
            "link": "http://localhost:8080/rest/items/DemoNumber5",
            "state": "1",
            "stateDescription": {
              "pattern": "%.0f",
              "readOnly": false,
              "options": [
                {
                  "value": "0",
                  "label": "Zero"
                },
                {
                  "value": "1",
                  "label": "One"
                },
                {
                  "value": "2",
                  "label": "Two"
                }
              ]
            },
            "commandDescription": {
              "commandOptions": [
                {
                  "command": "0",
                  "label": "Zero"
                },
                {
                  "command": "1",
                  "label": "One"
                },
                {
                  "command": "2",
                  "label": "Two"
                }
              ]
            },
            "type": "Number",
            "name": "DemoNumber5",
            "label": "DemoNumber5",
            "category": "battery",
            "tags": [],
            "groupNames": [
              "DemoSwitchGroup"
            ]
          },
          "widgets": []
        }
````

**Comment by mueller-ma** [comment]
@lolodomo Can you have a look at this PR and my question above as you implemented this change for Basic UI?

**Comment by lolodomo** [comment]
Display the value only if labelSource is SITEMAP_WIDGET and label contains a non empty pattern.

**Comment by lolodomo** [comment]
I have just a doubt if label in API response will not inherit the value from the default state pattern... even if not pattern is set in the label set in the sitemap.

**Comment by mueller-ma** [comment]
> Display the value only if labelSource is SITEMAP_WIDGET and label contains a non empty value inside [].

That's true in both cases from the JSON above. 

````
          "label": "Switch no pattern [One]",
          "labelSource": "SITEMAP_WIDGET",          
		  
	  "label": "Switch _%s_ [_One_]",
          "labelSource": "SITEMAP_WIDGET",
````

But according to your screenshot in https://github.com/openhab/openhab-webui/pull/2579#issuecomment-2118788344 only the value for the widget `_One_` should be shown.

**Comment by lolodomo** [comment]
Probably because the label in the API response is extended with the value coming from the default state pattern.
To say that differently, you probably do not have a way to get the exact label that was defined on the sitemap element.
In that case, I currently see no solution for you.

**Comment by mueller-ma** [comment]
Ok, so your change in Basic UI cannot be implemented in other client?

**Pull request closed without merging**
