### PR TITLE
Add a common base class for view holders displaying label + value.

### LINKED ISSUE #233: Formatting label text output for Android app
Hi,

I am using a the following item definitions to create a couple of switches:

Switch  LRBlindsetting  "Blinds are [MAP(blinds.map):%s]"   <rollershutter> (GF_Living) 
Switch  LRBlindmode "Auto [%s]" <light>

The web view of these switches look as desired:

webpage

However, the Android app view has square brackets around the output status (Open/Closed and Off/On):

android

Can anyone explain how I can get rid of the square brackets on the Android app display without messing up the web view?

I am using OpenHAB 1.8.3 and Android 6.0.1

Thanks,
Gibber
##

### PR DESCRIPTION
**Pull request by maniac103**
More precisely, use that base class for all cases where the server
provided label is likely to use the 'label [value]' syntax.
While doing so, add a separate value view for switch, slider and
rollershutter items.

Closes #233, #767

Signed-off-by: Danny Baumann <dannybaumann@web.de>

### CODE REVIEW

**Comment by maniac103** [comment]
The following view holder types are left with (potentially) showing the value in square brackets:
- FrameViewHolder
- ColorViewHolder
- MapViewHolder
- GenericViewHolder

As the first three don't have values that can meaningfully be shown and the latter is a catch-all fallback for items unknown at the time of compiling the used app version, this seems fine to me?

**Comment by mueller-ma** [comment]
> this seems fine to me?

Seems also fine to me, but I haven't looked at the code yet.

**Comment by mueller-ma** [comment]
For color and mapview items the value part shouldn't be shown when it's present in the label to have a consistent behavior with the basic ui.

**Comment by maniac103** [comment]
Done.

**Comment by mueller-ma** [comment]
@maniac103 Can you resolve the conflict?

**Comment by maniac103** [comment]
Sure. Will do that tomorrow.

**Comment by maniac103** [comment]
@mueller-ma Something's up with travis ... license for android-27 not accepted (?)

**Comment by mueller-ma** [comment]
It seems that the removed sdkmanager call accepted the license. According to the travis docs it should accept all licenses, but that doesn't work. Can you re-add the line in travis.yml?

**Comment by maniac103** [comment]
Oops. I'll update the tests.

**Pull request merged**
