### PR TITLE
Improve icons

### PR DESCRIPTION
**Pull request by mueller-ma**
* Use outline icons
* Remove some icons from preferences
* Make push status icon depending on status
* Use SVG for shortcut icon foreground

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

TODO:

- [x] Replace Tree with Tree-outline
- [x] NFC search and NFC disabled icon for WriteTagActivity
- [x] Update widget previews

### CODE REVIEW

**Comment by mueller-ma** [comment]
@maniac103 Do you want to review this?

**Comment by maniac103** [comment]
Huh, I didn't notice that you finished this one. I'll have a look at how it looks with the new drawables ASAP.

**Comment by mueller-ma** [comment]
Did you find time to review this?

**Comment by maniac103** [comment]
Oops, sorry, I completely forgot about this one. Drawables look fine to me, just should prune now-unused drawables. ic_color_lens_orange_340dp is one I noticed, didn't check for more at the moment.

**Comment by mueller-ma** [comment]
I've gone through all icons and removed unused ones. `ic_color_lens_orange_340dp` is used in the intro.

**Pull request merged**
