### PR TITLE
Fix possible NPE

### PR DESCRIPTION
**Pull request by mueller-ma**
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by mueller-ma** [comment]
Stacktrace:
screenshot_20190206-222209

I'm not sure how to reproduce this since `loadSitemapIcon()` isn't called if `mServerProperties` is null. The only case I can imagine is when the device has been rotated and `mServerProperties` is restored, but the connection not fetched.

**Comment by maniac103** [comment]
> I'm not sure how to reproduce this since `loadSitemapIcon()` isn't called if `mServerProperties` is null. The only case I can imagine is when the device has been rotated and `mServerProperties` is restored, but the connection not fetched.

In that case the connection must have changed during the rotation though!?
https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java#L229

I wonder whether this is a race condition where the connection went away during server property fetch?

I wonder whether we shouldn't check mConnection for being null in the `if` check in `loadSitemapIcon` instead? Somehow I feel we had a similar issue in the past, this feels somewhat familar to me...

**Comment by mueller-ma** [comment]
> I wonder whether we shouldn't check mConnection for being null in the `if` check in `loadSitemapIcon` instead?

Like this: https://github.com/openhab/openhab-android/commit/53a8c3bc7f1878bc5bff1517954d77c8e88a4f11?

**Comment by maniac103** [comment]
Yes. IIRC I shot it down back then (right?), but I now really think it's the best solution.

**Comment by mueller-ma** [comment]
No, you didn't, but I thought it's better to have null checks for mConnection and mServerProperties in one place.

**Comment by mueller-ma** [comment]
Stickler issues seem false-positive to me.

**Pull request merged**
