### PR TITLE
Next try to fix snackbar related crashes

### PR DESCRIPTION
**Pull request by mueller-ma**
````
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at java.util.ArrayList.remove(ArrayList.java:512)
       at kotlin.collections.CollectionsKt__MutableCollectionsKt.removeFirstOrNull(MutableCollections.kt:248)
       at org.openhab.habdroid.ui.AbstractBaseActivity$showSnackbar$1.invoke(AbstractBaseActivity.kt:169)
       at org.openhab.habdroid.ui.AbstractBaseActivity.showSnackbar(AbstractBaseActivity.kt:197)
       at org.openhab.habdroid.ui.AbstractBaseActivity.showSnackbar$default(AbstractBaseActivity.kt:162)
       at org.openhab.habdroid.ui.MainActivity.showPushNotificationWarningIfNeeded(MainActivity.kt:1085)
       at org.openhab.habdroid.ui.MainActivity$showPushNotificationWarningIfNeeded$1.invokeSuspend(:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
````

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by maniac103** [comment]
I don't think synchronizing helps at all here, since there's only one thread involved in UI updates anyway.

**Comment by JohannesPtaszyk** [comment]
Is there a way to reproduce this issue?

**Comment by mueller-ma** [comment]
> Is there a way to reproduce this issue?

No, I haven't found a way to reproduce this crash.

**Comment by JohannesPtaszyk** [comment]
I see. Somehow unfortunate issue. But as @maniac103 mentioned I also do not think synchronizing will help.

**Pull request closed without merging**
