### PR TITLE
Do not require users to have to manually click videos for playback.

### PR DESCRIPTION
**Pull request by digitaldan**

### CODE REVIEW

**Comment by digitaldan** [comment]
This ensures our video widget is able to playback video without requiring user interaction.

**Comment by digitaldan** [comment]
Thanks @mueller-ma for the changes, my java habits are hard to break !

**Comment by mueller-ma** [comment]
I guess you tested this code? I'll merge when the CI passes.

**Comment by digitaldan** [comment]
I did, i have lots of video widgets in my UI.

**Pull request merged**
