### PR TITLE
Improve connection check reachablility

### PR DESCRIPTION
**Pull request by mueller-ma**
Don't fail on a timeout instantly, but increase the retry count.

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by maniac103** [comment]
What's the use case for this ... IOW, in which cases does that help?

**Comment by mueller-ma** [comment]
On one device I get SocketTimeoutExceptions quite often, but not always, when I open the app. Currently if the first connection attempt throws a timeout exception, we wait 1 second in total. Ten retries in total need 2 seconds. Instead of failing after the first timeout, increase `retries` by 5 (5*200 == 1000). This way the function won't run longer than before.

**Comment by maniac103** [comment]
It will (potentially) run a bit longer than before: imagine a timeout happening every time; it will run 4 seconds (1 second timeout x 4 runs [with retries being 0, 5, 10 and 15]). Probably not that much of a big deal (and can be fixed by increasing by 10), I was just wondering _why_ that would happen.

**Comment by mueller-ma** [comment]
> I was just wondering why that would happen

I guess this is an issue with my Nexus 9 running Lineage 14, maybe due to some too aggressive power-saving WiFi disconnects. I don't have this issue with other devices on the same WiFi and openHAB server.

**Comment by maniac103** [comment]
OK, fair enough. Is doubling the check time in case of actual failure OK though? Why not keep `retries` at 10 and increase by 3 or 4 in case of timeout?

**Comment by mueller-ma** [comment]
Ok, I reverted the max retries back to 10.

**Pull request merged**
