### PR TITLE
Add up/down buttons to setpoint widgets

### PR DESCRIPTION
**Pull request by mueller-ma**
Edit: This adds a setting that allows switching between the old (with up/down
buttons) and new (with dialog) setpoint widgets.

### CODE REVIEW

**Comment by mueller-ma** [comment]
I want to keep this PR small, so only the setpoint item will be changed. Please note, that the current commit doesn't support switching between the different widget types.
My first approach was to set the visibility of the buttons, but it turned out to be pretty ugly, because I had to change the padding in the code. I created additional layouts. The only way to select the layout I see is to get the correct layout in onCreateViewHolder() and pass it via SetpointViewHolder(), but then I don't know how the change the layout w/o restarting the app.

**Comment by maniac103** [comment]
You can't change the layout of a view holder at runtime. Best idea is to create two different view holder types (as in number constants); you can use the same class for both.

**Comment by mueller-ma** [comment]
> (as in number constants)

I'm not sure where exactly you reffer to.

**Comment by maniac103** [comment]
I'm referring to the numbers returned by `getItemViewType()`

**Comment by mueller-ma** [comment]
@maniac103 Do you prefer having three xml layout files or one and hide the unneeded components in code?

**Comment by maniac103** [comment]
Didn't you say you need different layout files because of different paddings? If it's just visibility I'd prefer one layout file, I think, as we then don't need multiple item view types.

**Comment by mueller-ma** [comment]
Padding could be done in code as well, but that would be quite hacky.
Thinking about the preference to change the type: I'm not sure if a per user setting is really useful. For some items the dialog might be better, for some other ones the plus/minus buttons. What about dropping the preference entirely and having always dialog and buttons?

**Comment by maniac103** [comment]
> What about dropping the preference entirely and having always dialog and buttons?

Sounds fine to me. Move dropdown button to the left of the up/down buttons?

**Comment by mueller-ma** [comment]
I assigned an ID to the linear layout and assigned an onClickListener to this ID. However if I click on light blue areas, the default click animation is shown, but the dialog isn't opened.
Screenshot_2019-03-31-13-07-14

**Comment by maniac103** [comment]
@mueller-ma Please see my 4 commits on top of your additions at https://github.com/maniac103/openhab.android/commits/550-selection

**Comment by mueller-ma** [comment]
I had the same idea to implement an onRowClicked() function to fix long-clicking on setpoints (for nfc) not working anymore. I'll review soon.

**Comment by mueller-ma** [comment]
Using the demo package => "Widget Overview" => Temperature setpoint: If I increment it to `28.0°C` and then click on the down button, nothing happens. This is, because `state` in line 840 is 28 as int, not float. Side effect of  #1269?

**Comment by maniac103** [comment]
Sounds like it ... did you check the state in rest API response and/or SSE event?

**Comment by maniac103** [comment]
I've added another commit for the click handling, please pull: https://github.com/maniac103/openhab.android/commit/733cf7d09c61edcca6def47640a590c2e370fe5e ... it gives page opening precedence over dialog opening in the (admittedly unlikely) case a page link exists for the setpoint widget ... I'm not sure it's actually possible to achieve that, but better be safe than sorry ;-)

As for the float vs. int thing, it seems to work just fine for me using the current code in the branch. I'd suspect https://github.com/openhab/openhab-android/pull/1052/commits/a1e4ce15f0240826b7ff4dfe501b43b15d28badd has fixed it.

**Comment by mueller-ma** [comment]
> I'd suspect a1e4ce1 has fixed it.

Strange, it's fixed for me now. Maybe I just had an old branch.

**Pull request merged**
