### PR TITLE
Convert GcmRegistrationService to a JobIntentService.

### LINKED ISSUE #953: Crash on network change if app is in background on API 24+
### Actual behaviour
The app crashes if it's in background, the network changes (e.g. Wifi drops out) and it's running on a device running Android Oreo or newer.

### Expected behaviour
App shouldn't crash

 
### Steps to reproduce
See above.

### Can you reproduce the issue in demo mode?
Crash is unrelated to connected server

#### Client
* Android version: 8.1
* Device model: Oppo R7 Plus
* Stock or customized ROM: LineageOS 15.1
* App version : 2.2.10 beta
* Build flavor : Full
* Device language: DE

#### App log
```
07-16 21:52:15.579 W/ActivityManager(21878): Background start not allowed: service Intent { act=org.openhab.habdroid.action.REGISTER_GCM cmp=org.openhab.habdroid/.core.GcmRegistrationService } to org.openhab.habdroid/.core.GcmRegistrationService from pid=15396 uid=10214 pkg=org.openhab.habdroid
07-16 21:52:15.583 D/AndroidRuntime(15396): Shutting down VM
07-16 21:52:15.587 E/AndroidRuntime(15396): FATAL EXCEPTION: main
07-16 21:52:15.587 E/AndroidRuntime(15396): Process: org.openhab.habdroid, PID: 15396
07-16 21:52:15.587 E/AndroidRuntime(15396): java.lang.IllegalStateException: Not allowed to start service Intent { act=org.openhab.habdroid.action.REGISTER_GCM cmp=org.openhab.habdroid/.core.GcmRegistrationService }: app is in background uid UidRecord{15ba96b u0a214 RCVR idle change:uncached procs:1 seq(0,0,0)}
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at android.app.ContextImpl.startService(ContextImpl.java:1477)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at org.openhab.habdroid.core.CloudMessagingHelper.onConnectionUpdated(CloudMessagingHelper.java:30)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at org.openhab.habdroid.core.connection.ConnectionFactory.handleCloudCheckDone(ConnectionFactory.java:444)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at org.openhab.habdroid.core.connection.ConnectionFactory.handleMessage(ConnectionFactory.java:304)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at android.os.Looper.loop(Looper.java:164)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at java.lang.reflect.Method.invoke(Native Method)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
07-16 21:52:15.587 E/AndroidRuntime(15396): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### PR DESCRIPTION
**Pull request by maniac103**
Otherwise crashes might occur when app is in the background and
connectivity changes on Android 8+.

Fixes #953

Signed-off-by: Danny Baumann <dannybaumann@web.de>

### CODE REVIEW

**Comment by mueller-ma** [comment]
I tested this on Android 7: Wifi was enabled, notification received. Then I disabled wifi and I was still able to receive notifications.

**Comment by maniac103** [comment]
Can you check logcat for lines with GcmRegistrationService tag? There should be such lines after each connection change.

**Comment by maniac103** [comment]
Thinking about it, the only reason to re-register is the GCM token refresh, ither than that only a single register cycle is required. Will send a separate PR for that.
This PR needs to be updated so that the instance ID service also takes the work enqueue path. Will do so tomorrow.

**Comment by mueller-ma** [comment]
> Can you check logcat for lines with GcmRegistrationService tag? There should be such lines after each connection change.

Sometimes after a connection change I can see
````
08-18 20:39:38.841 16151-20941/org.openhab.habdroid D/GcmRegistrationService: Register device at openHAB-cloud with URL: addAndroidRegistration?deviceId=....
08-18 20:39:39.063 16151-20941/org.openhab.habdroid D/GcmRegistrationService: GCM reg id success
````

but not after every. Notifications are always working.

**Comment by mueller-ma** [comment]
@maniac103 Do you think this is ready for the next beta version?

**Comment by maniac103** [comment]
@mueller-ma Yeah, I think so. It still can be optimized, but should work well enough for now.

**Pull request merged**
