### PR TITLE
Use format specifier also when updating non-UoM items.

### PR DESCRIPTION
**Pull request by maniac103**
See
https://community.openhab.org/t/slider-items-with-new-android-app-2-8-0-not-working-anymore/79344/5

### CODE REVIEW

**Comment by mueller-ma** [comment]
Currently I cannot test this. Is it RTM from your side and have you tested it?

**Comment by maniac103** [comment]
It's RTM from my point of view. I haven't explicitly tested it (yet), but the logic change is pretty simple; it IMHO is safe for a Beta at least.

**Comment by mueller-ma** [comment]
Can you upload a debug apk to https://community.openhab.org/t/slider-items-with-new-android-app-2-8-0-not-working-anymore/79344?

**Comment by maniac103** [comment]
Sure, done.

**Pull request merged**
