### PR TITLE
Make app_name for beta builds translatable

### PR DESCRIPTION
**Pull request by mueller-ma**
There might be a language where the word "Beta" is usually translated.
Is it in English `openHAB Beta` or `openHAB beta`?

### CODE REVIEW

**Comment by maniac103** [comment]
Does this actually work with Crowdin (a nontranslatable string overlaid with a translatable one)?

**Comment by mueller-ma** [comment]
I think so, as both strings are in different files. See: https://crowdin.com/project/openhab-android/de#

**Comment by maniac103** [comment]
OK, if that works, fine with me :-)

**Comment by mueller-ma** [comment]
With the crowdin config you can wait for #775 as that pr introduces new strings files.

**Pull request merged**
