### PR TITLE
Remove pullapprove

### PR DESCRIPTION
**Pull request by mueller-ma**
Pullapprove's v2 api has been depricated and v3 doesn't offer a
sign-off-by check.
Replaced by https://probot.github.io/apps/dco/

### CODE REVIEW

**Comment by mueller-ma** [comment]
@kaikreuzer Can you accept the request to add https://probot.github.io/apps/dco/ and remove pullapprove?

**Comment by kaikreuzer** [comment]
Accepted DCO, but could not see Pullapprove being used anywhere...

**Comment by mueller-ma** [comment]
Pullapprove should be in your account

**Comment by kaikreuzer** [comment]
I guess Pullapprove simply won't be active anymore, when this PR is merged, because it is looking for the yml file. We still use it on other repos, so I don't want to revoke access from my account right now.

**Pull request merged**
