### PR TITLE
Change user agent to "openHAB client for Android"

### PR DESCRIPTION
**Pull request by mueller-ma**
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by mueller-ma** [comment]
@maniac103 Any idea why this fails in Travis, but works fine on my machine?
````
:mobile:compileFossStableDebugJavaWithJavac/home/travis/build/openhab/openhab-android/mobile/src/main/java/org/openhab/habdroid/util/HttpClient.java:39: error: cannot find symbol
        headers.put("User-Agent", "openHAB client for Android");
        ^
  symbol:   variable headers
  location: class HttpClient
````

**Comment by maniac103** [comment]
Not really, this doesn't seem to make sense :-/ Any weird whitespace or other unusual characters maybe?

**Comment by maniac103** [comment]
Not really, this doesn't seem to make sense :-/ Any weird whitespace or other unusual characters maybe?

**Comment by mueller-ma** [comment]
The variable `headers` has been removed in #940 and Travis builds the merged commit.

**Comment by maniac103** [comment]
Ah, so Travis auto-rebases? OK, makes sense then.

**Comment by mueller-ma** [comment]
Travis uses the merge that is autogenerated by Github. This is why travis doesn't build, if a PR has merge conflicts.

**Comment by mueller-ma** [comment]
> Rather than build the commits that have been pushed to the branch the pull request is from, we build the merge between the source branch and the upstream branch.

https://docs.travis-ci.com/user/pull-requests/

**Pull request merged**
