### PR TITLE
Enable twopane mode for portrait

### PR DESCRIPTION
**Pull request by mueller-ma**
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by maniac103** [comment]
Got a screenshot of how it looks in portrait?

**Comment by mueller-ma** [comment]
From my 7 inch tablet:
screenshot 1
screenshot 2
screenshot 3
screenshot 4
screenshot 5
screenshot 6

I'll checked it with emulators: The twopane mode isn't used on Nexus 5 and 6, but on Nexus 7 and generic 10 inch tablet.

**Comment by maniac103** [comment]
For 10" it's fine IMHO, but I'm not sure whether 7" portrait really also should get two pane...

**Comment by mueller-ma** [comment]
I'm also not convinced about 7 inch portrait. I'll try 7 inch landscape and 10 inch portrait and landscape.

**Pull request merged**
