### PR TITLE
Do not access static member via instance reference

### PR DESCRIPTION
**Pull request by FlorianSW**

### CODE REVIEW

**Comment by FlorianSW** [comment]
Uhm, is it correct, that codecov is "filing" when the coverage is decreased?

**Comment by maniac103** [comment]
Please see #498.

**Comment by FlorianSW** [comment]
Ok, that would fix the second access, however, the first one still applies :)

**Comment by maniac103** [comment]
Yes, of course :-) I just wanted to point out the second potential conflict.

**Comment by mueller-ma** [comment]
The mentioned PR is merged, can you remove the second fix?

**Comment by mueller-ma** [comment]
> Uhm, is it correct, that codecov is "failing" when the coverage is decreased?

It works as intended, but the question is, if it should fail when someone does only small changes to the code.

**Comment by FlorianSW** [comment]
Done!

**Pull request merged**
