### PR TITLE
Use time for notification time

### LINKED ISSUE #663: Notification time should be event time
Currently, the time that is shown in the notifications is the time when the notification was received by the device not the actual event time.

How to reproduce:
Set device to flight mode, send notification, wait a minute, go back online.

It should be be enough to add a `.setWhen(time_in_millis)` in GcmIntentService. Event time should be part of the message already.

### PR DESCRIPTION
**Pull request by cribskip**
Signed-off-by: Sascha Kloß <sascha.kloss@gmx.de>

Fixes #663 

**WARNING**
I could not get GCM working in the emulator, so this is untested but should work just fine.

### CODE REVIEW

**Comment by mueller-ma** [comment]
@cribskip Can you rebase your PR to get rid of all the falsy reported @stickler-ci errors?

**Comment by redeye86** [comment]
I tried to find a solution myself (c.f https://github.com/openhab/openhab-android/commit/7104cce9a8a5b4b2ae67e05389205a38308d81e6) and confirmed that it is working on my device. It seems that somewhere in the cloud service some information (time, severity, ...) is lost and not passed to android. In my implementation i used "google.sent_time", which is the time the gcm servers received the message from openhab cloud servers. This is not the actual event time, but i think the notifications are forwarded immediately anyway. I guess it would be best to use "time" if present (in case it gets implemented in the cloud service), otherwise "google.sent_time" and finally System.currentMillis() as a fallback.

**Comment by cribskip** [comment]
@redeye86 Thanks, your implementation is sleeker than mine, this should be used.

@mueller-ma Please go for #673

**Comment by maniac103** [comment]
> and finally System.currentMillis() as a fallback.

That's the default the Android framework chooses anyway if setWhen() isn't called. I'd call the timestamp extra rather `timestamp` instead of `time`, but I'd agree it would make sense to add it if there's a chance of implementing it in the cloud service (is this information available there?) ... currently it isn't sent: https://github.com/openhab/openhab-cloud/blob/master/app.js#L411

**Pull request closed without merging**
