### PR TITLE
Improve setpoint look

### PR DESCRIPTION
**Pull request by mueller-ma**
* Change arrow color to white (taken from
https://github.com/maniac103/openhab.android/commit/b824cd31253aaa813fa6ee7f98b5c99107be128d)
* Change arrow width to match selection items

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by maniac103** [comment]
screenshot_1520342217

Illustrates the (new) difference between selection and setpoint.

**Comment by mueller-ma** [comment]
screenshot_2018-03-06-10-26-54
screenshot_2018-03-06-14-00-39

**Comment by maniac103** [comment]
Is that tablet on L by any chance? I think I saw this issue on an L emulator before...
But in any case, in your screenshot it's the selection widget that needs to be fixed, not the setpoint one. The color change is obviously fine though.

**Comment by mueller-ma** [comment]
Yes, that device run 5.1.1.
I'll have to test it on another device.

**Comment by mueller-ma** [comment]
See https://github.com/openhab/openhab-android/issues/747 for the selection widget.

**Pull request merged**
