### PR TITLE
Change icon of openhab notifications to the new one

### LINKED ISSUE #563: Notifications still have the old logo
Push notifications displayed by the app still sport the old openHAB logo: I believe it is [ic_stat_openhab_bw.png](https://github.com/openhab/openhab.android/blob/master/mobile/src/main/res/drawable-xhdpi/ic_stat_openhab_bw.png) (available in different dpis, this is the xhdpi version).

### PR DESCRIPTION
**Pull request by FlorianSW**
Fixes #563

### CODE REVIEW

**Comment by mueller-ma** [comment]
When you have a really close look, you can see that the icon is autoscalled by your device and that doesnt look good. Can you include a svg version of the icon and use that?
icon

@kaikreuzer Can you upload a svg of the icon without text?

**Comment by kaikreuzer** [comment]
@mueller-ma Will this do? [openHAB_appicon.svg.zip](https://github.com/openhab/openhab.android/files/1595124/openHAB_appicon.svg.zip)

**Comment by FlorianSW** [comment]
That's perfect :) Thanks!

**Comment by mueller-ma** [comment]
I thought svg makes it better, but thats not the case:
screenshot_2018-01-01-17-54-30

**Comment by maniac103** [comment]
Just make the vector drawable 24x24dp.

**Comment by FlorianSW** [comment]
Having a 24x24dp is more difficult (I would like to get rid of the png logo, too), as the introduction slides uses the image, too, however, it will use the Drawable as a res-reference, not as a Drawable object where we can resize it. I'll take a look into it to check if that can be changed. Otherwise I'll re-add the png for the intro slide.

**Comment by maniac103** [comment]
Just add the drawable twice (one as 24x24, one as 340x340). One could scale the drawable if it really were vector, but for Android < 5.0 Android Studio produces PNGs from the XMLs, and scaling those would look ugly.

**Comment by mueller-ma** [comment]
LGTM!

**Pull request merged**
