### PR TITLE
Update screenshots in docs

### PR DESCRIPTION
**Pull request by mueller-ma**
Pixel 2 frame, generated with https://developer.android.com/distribute/marketing-tools/device-art-generator

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by mueller-ma** [comment]
@Confectrician Is there a way to preview this change? I want to display the screenshots in a row.

**Comment by Confectrician** [comment]
Nope or at least there is no known to me.
We could check if the vuepress style is documented and has some grid system which we could use through a html class attribute.

**Comment by mueller-ma** [comment]
Ok, we'll see...

**Comment by Confectrician** [comment]
I have rescheduled the jenkins job that will fetch the external ressources, so we dont have to wait too much.

**Comment by Confectrician** [comment]
https://github.com/vuejs/vuepress/issues/578

working with html is basically the correct way, when we want to use no special extension that add resizing to the supported markdown features.

**Comment by Confectrician** [comment]
Looks good 👍 

https://www.openhab.org/docs/apps/android.html

**Comment by mueller-ma** [comment]
Nice :+1:

**Pull request merged**
