### PR TITLE
Improve chart activity

### PR DESCRIPTION
**Pull request by mueller-ma**
* Add voice recognition
* Hide widget value in title
* Don't show legend for single items if legend is not set

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by maniac103** [comment]
Legend and title changes make sense to me, but I'm not sure about the voice recognition one. I somewhat doubt we need it in ChartActivity, since that one (IMHO) is a short-lived one that's only shown temporarily. Is there a specific reason for adding that functionality?

**Comment by mueller-ma** [comment]
Yes, I added voice recognition is preparation for https://github.com/openhab/openhab-android/issues/1841#issuecomment-593146432.

**Comment by maniac103** [comment]
For that purpose I wouldn't use ChartActivity as-is anyway though, but rather refactor its logic into a fragment and make the activity a thin wrapper around that fragment.

**Comment by mueller-ma** [comment]
Makes sense. I've removed the voice recognition.

**Pull request merged**
