### PR TITLE
Fix split screen mode

### PR DESCRIPTION
**Pull request by mueller-ma**
Both entries were added to the manifest, but no code was added to
support these features.

See #724

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

As this PR doesn't really fix the issue, I'll wait for a real fix and only merge this PR, if the bug isn't fixed until the next release.

### CODE REVIEW

**Comment by maniac103** [comment]
@fat-tire As you introduced those flags, any comments?

**Comment by mueller-ma** [comment]
By adjusting minHeight and minWidth the values are now visible for me. However the app sometimes reloads when resizing and leaves the subpage.

**Comment by maniac103** [comment]
> However the app sometimes reloads when resizing and leaves the subpage.

This will probably get better with #688.

**Comment by fat-tire** [comment]
Hey sorry to come in late-- I'm not sure if there's a way to enable resizable windows (kind of a necessity for Chromebooks) but disable split screen.  i think they're both using the same setting in the manifest...  But it sounds like you guys are on it :)

**Pull request merged**
