### PR TITLE
Fix PreferencesActivity crash on API < 17

### PR DESCRIPTION
**Pull request by mueller-ma**
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by maniac103** [comment]
I wonder whether simply calling just `isFinishing()` wouldn't be sufficient here?

**Comment by mueller-ma** [comment]
Good question. Since I cannot reproduce this crash, I've looked up on the Internet and found this fix.

**Comment by maniac103** [comment]
Probably could/should check `FragmentManager.isStateSaved()` instead, and move the check into the respective case statement.

**Comment by mueller-ma** [comment]
`FragmentManager.isStateSaved()` isn't available on all API levels we support. This would require us changing the whole PreferenceActivity to use the AppCompat version of PreferenceFragment.

**Comment by maniac103** [comment]
Wouldn't that be a good either either way anyway? ;-)

**Comment by mueller-ma** [comment]
Definitely, but that's a larger task and I want to focus on the pending PRs and #257 for now. It's tracked in https://github.com/openhab/openhab-android/issues/1295.
I removed the `isDestroyed()` call.

**Pull request merged**
