### PR TITLE
Add hint why connection is marked as insecure

### LINKED ISSUE #2000: Add info why connection is marked as insecure
### Is your feature request related to a problem? Please describe.
When using http or no authentication, the connection summary in the settings says "Insecurely connected to example.com". Some users think it's insecure, because they didn't configure a ssl client cert.

### Describe the solution you'd like
Add a info pref to the local and remote connection subscreen explaining why the connection is marked as insecure.

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #2000

I'm not sure about the prefs title, it could be dropped.

### CODE REVIEW

**Review by maniac103 — COMMENTED** [review]
I don't really like this approach. If we add a second pref with the security hint, we could as well put the same hint to the location connection pref summary. I'm not sure it's really needed either, since the reason becomes obvious once the user enters the connection prefs.

**Comment by mueller-ma** [comment]
> I'm not sure it's really needed either, since the reason becomes obvious once the user enters the connection prefs.

Some people think their connection is marked as insecure, because they don't provide a ssl client certificate. This is the reason I want to add some additional hint.

> If we add a second pref with the security hint, we could as well put the same hint to the location connection pref summary.

That might be a better solution. I give it a try.

**Comment by JohannesPtaszyk** [comment]
> I don't really like this approach. If we add a second pref with the security hint, we could as well put the same hint to the location connection pref summary. I'm not sure it's really needed either, since the reason becomes obvious once the user enters the connection prefs.

I actually think it is a nice addition to add a hint here. I know some people that got confused by the insecure connection.

**Comment by mueller-ma** [comment]
> If we add a second pref with the security hint, we could as well put the same hint to the location connection pref summary.

Done

**Pull request merged**
