### PR TITLE
Refresh only upgraded widgets, not all the fragments (Replace ListVie…

### PR DESCRIPTION
**Pull request by 9a4gl**
…w with RecyclerView)

Signed-off-by: Tihomir Heidelberg <tihomir.heidelberg@lite.hr>

### CODE REVIEW

**Comment by mueller-ma** [comment]
I looked at the travis build. Seems that it fails because of the missing sitemap selection. Can you rebase your PR?

**Comment by 9a4gl** [comment]
I have rebased. Same problem. I have checked the test case, it is not related to my code. It must be failing on master, too.

**Comment by 9a4gl** [comment]
I rebased, but it is failing on other place. This place may be related to my change, but unfortunately I was not able to solve that locally as I do not have much knowledge about this testing framework. Just replacing list id with recylcerView id didnd't help. @mueller-ma do you know who can help/fix this ?

**Comment by maniac103** [comment]
I've submitted an alternative RecyclerView conversion, which significantly cleans up the mess that getView() is right now: https://github.com/openhab/openhab-android/pull/650

**Comment by 9a4gl** [comment]
Refactoring has been done in #650, but initial problem that widgets refresh when not necessary still exists !

**Pull request closed without merging**
