### PR TITLE
Fix up SVG rendering.

### LINKED ISSUE #913: SVG with height and width attributes aren't shown correctly
### Actual behaviour
See https://community.openhab.org/t/version-2-1-toast-messages-for-the-voice-input/44436/4
 
### Steps to reproduce
1. Use the icon provided in the thread.

### Can you reproduce the issue in demo mode?

No

The issue is that the icon has a larger height than the viewport dimens that are used for [creating the drawable](https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java#L136). Having a fixed heigth for icons seems wrong to me as every ui should scale the icons according to the available space. I guess the best fix would be to remove the height and width from the svg before it's rendered by the svg lib.

### LINKED ISSUE #2021: None-square SVG files don't render correctly
### Actual behaviour
Non-square-SVG files (e.g. viewBox="0 0 1200 1000") don't render properly (scaling is off, part of image is off screen, see picture). Square images render fine.

### Expected behaviour
Rendering should as in attached image (patched version of the code, see attached).
A user workaround is of course to make the SVG square.

### Steps to reproduce
Render attached SVG. 

### Can you reproduce the issue in demo mode?
Yes, by replacing chart.png with chart.svg for weather_chart

#### Client
* Android version: multiple (7.x, 8.x, 9.x, 10.x)
* Device model: at least 8 different phones and tablets
* App version : most recent stable and beta (2.12.20-beta)
* Build flavor : 
* Device language: english

#### Server
* Server version: 2.5.5
* Reverse Proxy: 
* Authentication method : 

I think I discovered where the issue is: in [ExtensionFuncs.kt](https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt)

```
        if (docWidth < 0 || docHeight < 0) {
            val aspectRatio = svg.documentAspectRatio
            if (aspectRatio > 0) {
                val heightForAspect = targetSize.toFloat() / aspectRatio
                val widthForAspect = targetSize.toFloat() * aspectRatio
                if (widthForAspect < heightForAspect) {
                    docWidth = Math.round(widthForAspect)
                    docHeight = targetSize
                } else {
                    docWidth = targetSize
                    docHeight = Math.round(heightForAspect)
                }
            } else {
                docWidth = targetSize
                docHeight = targetSize
            }
            // we didn't take density into account anymore when calculating docWidth
            // and docHeight, so don't scale with it and just let the renderer
            // figure out the scaling
            density = null
        }
        if (docWidth != targetSize || docHeight != targetSize) {
            val scaleWidth = targetSize.toFloat() / docWidth
            val scaleHeight = targetSize.toFloat() / docHeight
            density = (scaleWidth + scaleHeight) / 2
        }

        val bitmap = Bitmap.createBitmap(targetSize, targetSize, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)
        if (density != null) {
            canvas.scale(density, density)
        }
```
It's fixed by changing:
`        if (docWidth != targetSize || docHeight != targetSize) {`
to
`        if (docWidth != targetSize && docHeight != targetSize) {`
Basically there is no need for _density_ since properly build SVG images will autoscale fine and can preserve aspect ratio (e.g. with _preserveAspectRatio="xMidYMid meet"_) but I admit I don't fully understand the whole purpose of _canvas.scale(density, density)_

Screenshot_20200524-100919_openHAB_Beta
Screenshot_20200524-102338_openHAB_Beta
[chart.zip](https://github.com/openhab/openhab-android/files/4673176/chart.zip)

### PR DESCRIPTION
**Pull request by maniac103**
In particular, fix rendering of SVGs with explicit sizes and of
non-square SVGs.

Closes #2021
Closes #913

### CODE REVIEW

**Comment by maniac103** [comment]
I've verified this one against the SVGs in
- #728 
- https://community.openhab.org/t/svg-icons-in-the-android-app/46274/29
- https://community.openhab.org/t/version-2-1-toast-messages-for-the-voice-input/44436/6 (#913)
- #2021 (the zip attached there seems off, I used the one attached to #2022)

**Comment by mueller-ma** [comment]
I set up a sitemap page with four text items, one for each icon, and four image items, also one for each icon. Before the image item with the icon from #728 looked good, now it's pixelated.

**Comment by maniac103** [comment]
Well, that icon specifies it wants to have a size of 24x24, so my change obeys to that. Drop that explicit size and everything will be fine.
IMHO we should follow the icon's specifications instead of guessing what the icon author might have wanted and/or the user wants to be displayed.

**Comment by mueller-ma** [comment]
I didn't specify an explicit size in my sitemap, though: `Image url="http://openhab:8080/icon/svg_728?state=UNDEF&format=svg"`

> IMHO we should follow the icon's specifications instead of guessing what the icon author might have wanted and/or the user wants to be displayed.

Isn't this patch about not honoring the icon's specifications and instead display icons "100% height/width"? An explicit size caused the issue in https://community.openhab.org/t/svg-icons-in-the-android-app/46274/27, right?

**Comment by maniac103** [comment]
> I didn't specify an explicit size in my sitemap, though

OK, so the behavior you'd like to see for that icon when used as image is it being sized at 24x24dp instead of full width? If so, makes sense to me, I'll look into that.

**Comment by maniac103** [comment]
Additional question: may this be an artifact of our image caching? We cache by URL, so at the time the (large) image view requests the icon, there already might be a (small) icon view variant in the cache.

**Comment by mueller-ma** [comment]
Basic UI honors the size specified in the svg when used as image, but not when used as icon.
IMO it makes more sense to display the image with full width, when no size is specified.

> Additional question: may this be an artifact of our image caching? We cache by URL, so at the time the (large) image view requests the icon, there already might be a (small) icon view variant in the cache.

I'll check that.

**Comment by maniac103** [comment]
So how about this? I noticed we scaled up plain bitmaps to full width as well, so I also fixed that in the process.

**Comment by mueller-ma** [comment]
I like it, but users may complain and ask for a minimum size of images. We'll see.

> Before the image item with the icon from #728 looked good, now it's pixelated.

This is fixed now. The icon is displayed with 24x24 px and sharp.

> Additional question: may this be an artifact of our image caching? We cache by URL, so at the time the (large) image view requests the icon, there already might be a (small) icon view variant in the cache.

However the same icon as icon is now pixelated. Now I have a sitemap page with this icon as icon only, not as image. Even when I refresh the page, the icon is still pixelated. This isn't a caching issue since I can see in the logs that the icon is downloaded: `<-- 200 OK http://openhab:8080/icon/svg_728?format=SVG&anyFormat=true (35ms)`

> I didn't specify an explicit size in my sitemap, though

BTW: The image widget doesn't take a height parameter at all: https://www.openhab.org/docs/configuration/sitemaps.html#element-type-image

**Comment by maniac103** [comment]
> However the same icon as icon is now pixelated. Now I have a sitemap page with this icon as icon only, not as image. 

Yes, but that's the icon's fault. With numbers for a Pixel 3 emulator:
- display density is 440 dpi, thus `displayMetrics.density` is 2.75
- icon specifies its size as 24x24, thus it gets rendered at 24 * 2.75 = 66 pixels for each side
- that 66x66 pixels bitmap then gets stretched to a 132x104 pixels icon ImageView (*)

I don't see how we could avoid the pixelation without messing with the icon itself. If anybody complains, we can tell them 'fix yo icon' ... after all, icons without explicit document size will be rendered sharp.

(*) Do you know whether there's a specific reason for the icon ImageView to have top/bottom, but not left/right padding? That's where the difference in dimension comes from. Personally, I'd make the padding symmetric for all sides, which has the nice side effect of images with unconstrained sizes being rendered in the correct size. At the moment, I'm looking at the width only (here: 132px) and render at that size (here: 132x132), while the final image will be scaled by height (here: 104x104). I'm not looking at height due to the 'Image' item case, where width = match_parent and height = wrap_content, so without image height = 0.

**Comment by mueller-ma** [comment]
Honestly I think this PR makes SVG icon handling worse. Before icons without explicit size and with explicit size in the root `svg` tag only were rendered well. Many icons have an explicit size and I don't want the user to bother about that.

> I don't see how we could avoid the pixelation without messing with the icon itself.

Then I'd keep it as is.

> In particular, fix rendering [...] of non-square SVGs.

Seems good to me, but non-square SVGsare probably more seldom than SVGswith explicit size.

> Personally, I'd make the padding symmetric for all sides, which has the nice side effect of images with unconstrained sizes being rendered in the correct size.

Go for it 👍

**Comment by maniac103** [comment]
> Honestly I think this PR makes SVG icon handling worse. Before icons without explicit size and with explicit size in the root svg tag only were rendered well.

I respectfully disagree, since this PR fixes the cases in
- https://community.openhab.org/t/svg-icons-in-the-android-app/46274/29
- #2021

Which were plain broken before. Additionally, this PR gets us to a state where SVG rendering is 100% explainable and predictable. IMHO those points are much more important than a pixelated rendering under some circumstances.

Will make an additional commit though to make paddings symmetric. I'll also look at how BasicUI handles icons. We can add back your previous hack to force rendering them in icon view size, but as you can see in the forum link above, that hack also has its side effects ... and correctly sized, but blurry, icons are IMHO preferable over wrongly sized sharp ones.

**Comment by maniac103** [comment]
> I'll also look at how BasicUI handles icons.

BasicUI shows that icon at a smaller size instead of scaling it up. We can do the same if you prefer that. Personally I'm torn about which of the two is the better option.

**Comment by mueller-ma** [comment]
I didn't look at Basic UI before. The icons there aren't full size and sharp, so I think it's ok to do so in the app as well.

> BasicUI shows that icon at a smaller size instead of scaling it up. We can do the same if you prefer that. Personally I'm torn about which of the two is the better option.

I think it's easier to explain when the icons aren't scalled up. Otherwise we honor the explicit size during rendering, but not afterwards.

> We can add back your previous hack to force rendering them in icon view size, but as you can see in the forum link above, that hack also has its side effects

We could add it back, but only for icons that have a 1:1 ratio and no explicit sizes except the one in the root tag.

**Comment by maniac103** [comment]
> I think it's easier to explain when the icons aren't scalled up. Otherwise we honor the explicit size during rendering, but not afterwards.

That's true, but without scaling, it might become impossible to have consistent icon sizes between UIs. We use 40 'px' (dp actually), but who knows what exact value iOS and BasicUI use. I wonder whether making this optional would make sense, or is that too much?

**Comment by mueller-ma** [comment]
I wouldn't add a setting for that. If you add a section to the "Help and Technical Details" section in the docs, you can implement upscaling for icons.

**Comment by maniac103** [comment]
Added the docs, please let me know if that wording is OK.

**Comment by mueller-ma** [comment]
The docs LGTM.

What about my suggestion "We could add it back, but only for icons that have a 1:1 ratio and no explicit sizes except the one in the root tag."?

**Comment by maniac103** [comment]
> What about my suggestion "We could add it back, but only for icons that have a 1:1 ratio and no explicit sizes except the one in the root tag."?

Is there a way to determine whether that condition is true? I'm not sure TBH.

**Comment by mueller-ma** [comment]
I looked at the FAQ and there are three questions interesting for us, starting at https://bigbadaboom.github.io/androidsvg/faq.html#My_SVG_won't_scale_to_fit_the_canvas_or_my_ImageView
It basically says that SVGs are scaled up if the have a viewbox, but no explicit size. It's recommended to override the height/width attribute and set a viewbox if not present.

Something like:
````diff
diff --git a/mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt b/mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
index a8087c14..e297e640 100644
--- a/mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
+++ b/mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
@@ -156,6 +156,16 @@ fun InputStream.svgToBitmap(targetSize: Int): Bitmap {
         var density: Float? = displayMetrics.density
         val targetSizeFloat = targetSize.toFloat()

+        val height = svg.documentHeight
+        val width = svg.documentWidth
+        if (svg.documentViewBox == null && height > 0 && width > 0) {
+            svg.setDocumentViewBox(0F, 0F, width, height)
+        }
+        if (svg.documentViewBox != null) {
+            svg.setDocumentWidth("100%")
+            svg.setDocumentHeight("100%")
+        }
+
         svg.renderDPI = DisplayMetrics.DENSITY_DEFAULT.toFloat()
         var docWidth = svg.documentWidth * displayMetrics.density
         var docHeight = svg.documentHeight * displayMetrics.density

````

With this commit all four tested icons render sharp. When used as image items they're rendered too large (higher than the screen height), though.

**Comment by maniac103** [comment]
The former part (generate view box from width/height) seems fine to me (and is the fix for the printer icon). I don't want to do the latter part (discard width/height if view box is present) though, for the same reasons as with your original hack - it *is* your original hack after all. ;-) I'll add a parameter that passes conversion size preference (prefer source / prefer target) and let it toggle exactly that piece of code. For icons we can set it to 'prefer target', for images to 'prefer source'.

**Comment by mueller-ma** [comment]
Can you rebase this PR?

**Comment by maniac103** [comment]
Sure, I'll do it once I'm near a PC again.

**Pull request merged**
