### PR TITLE
Catch NPE in OSM library

### LINKED ISSUE #1443: App crashes because of issue in OSM library
# Project Information

* Repository:  https://github.com/openhab/openhab-android
* Project Name:  openhab-android
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://play.google.com/store/apps/details?id=org.openhab.habdroid

# Expected behavior

When I turn on toggle switch, the application should not be crashing, but when I turn off the button, it gets off 

# Actual behavior

The application crashes when I turn toggle switch on or off

#### How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=org.openhab.habdroid)the application
*  open the application
* click on Widget Overview
* Turn toggle switch on and off
* Note the Error

* Browser/App version: version 2.7.11 beta
* Operating system: 6.0

#### Logcat

<pre><code>D/AndroidRuntime(28653): Shutting down VM

E/AndroidRuntime(28653): FATAL EXCEPTION: main

E/AndroidRuntime(28653): Process: org.openhab.habdroid.beta, PID: 28653

E/AndroidRuntime(28653): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.osmdroid.views.MapView.getContext()' on a null object reference

E/AndroidRuntime(28653): 	at org.osmdroid.views.MapViewRepository.getDefaultMarkerIcon(MapViewRepository.java:74)

E/AndroidRuntime(28653): 	at org.osmdroid.views.overlay.Marker.setDefaultIcon(Marker.java:139)

E/AndroidRuntime(28653): 	at org.osmdroid.views.overlay.Marker.<init>(Marker.java:114)

E/AndroidRuntime(28653): 	at org.osmdroid.views.overlay.Marker.<init>(Marker.java:92)

E/AndroidRuntime(28653): 	at org.openhab.habdroid.ui.MapViewHelperKt.setMarker(MapViewHelper.kt:244)

E/AndroidRuntime(28653): 	at org.openhab.habdroid.ui.MapViewHelperKt.applyPositionAndLabel(MapViewHelper.kt:223)

E/AndroidRuntime(28653): 	at org.openhab.habdroid.ui.MapViewHelper$OsmViewHolder$bind$1.run(MapViewHelper.kt:101)

E/AndroidRuntime(28653): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(28653): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(28653): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(28653): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(28653): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(28653): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(28653): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(28653): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #1443

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by maniac103** [comment]
Can you repro this? From a look at the OSM code, I don't understand the reported  crash :-/

**Comment by mueller-ma** [comment]
Yes, I can reproduce (https://github.com/osmdroid/osmdroid/issues/1223#issuecomment-497972031). This happens if you have a subpage with MapView open, but the MapView isn't shown.

**Comment by maniac103** [comment]
Looks like a better fix would be calling `mapView.setDestroyMode(false)` which causes the view to not be irreversibly destroyed when it's detached.

**Comment by maniac103** [comment]
The Google Maps code uses lite mode for the list items to avoid the need for onDestroy. The equivalent for OSM is more complicated, as one needs to create + bind the bitmap semi-manually. See PR linked via https://github.com/osmdroid/osmdroid/issues/990 for a sample.

**Comment by mueller-ma** [comment]
Adding `mapView.setDestroyMode(false)` fixes this issue.
The "lite mode" requires the map to be fully loaded which can take some time, because the OSM tile servers are a bit slow. I want to avoid long waiting times and rather show a map that is loaded tile by tile.

**Comment by maniac103** [comment]
> I want to avoid long waiting times and rather show a map that is loaded tile by tile.

Fair enough. We'll need to watch out for OOMs being reported though, as without calling `onDestroy` we'll definitely leak memory.

**Pull request merged**
