### PR TITLE
Always use item options instead of mappings if available.

### LINKED ISSUE #1281: Switch widget with dynamic options
The app is not handling correctly the switch widget with dynamic options.

It handles static options with mappings defined in the sitemap by displaying a button for each mapping.

In case of dynamic options, it should display a button for each option too. Of course, it should do it only if the number of options is low. In Basic UI and Classic UI, the limit is set to 4 options (4 buttons). If there are 5 options or more, the widget is rendered as a simple switch.

Current behavior: dynamic options are ignored and a simple switch is displayed.

### PR DESCRIPTION
**Pull request by maniac103**
Closes #1281

### CODE REVIEW

**Comment by maniac103** [comment]
We may want to rework the segmented switch button layout before doing this, though ... it doesn't deal well at all with the options being larger than the available space.

**Comment by mueller-ma** [comment]
> We may want to rework the segmented switch button layout before doing this, though ... it doesn't deal well at all with the options being larger than the available space.

#1326?

Which binding do you use to generate the dynamic options?

**Comment by maniac103** [comment]
Yeah, that. I'm using the Squeezebox binding.

**Comment by mueller-ma** [comment]
@lolodomo Do you want to review this?
@maniac103 Can you rebase this?

**Comment by maniac103** [comment]
@mueller-ma Done.

**Comment by mueller-ma** [comment]
@maniac103 RTM? I didn't find a binding that has this feature and requires no hardware.

**Comment by maniac103** [comment]
@mueller-ma Taking aside the switch button layout, which has #1326, yes, IMHO it is.

**Pull request merged**
