### PR TITLE
Improve log output

### PR DESCRIPTION
**Pull request by maniac103**

### CODE REVIEW

**Comment by mueller-ma** [comment]
````
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: org.openhab.habdroid.beta, PID: 4825
    java.lang.NullPointerException: Attempt to invoke virtual method 'int okhttp3.Response.code()' on a null object reference
        at org.openhab.habdroid.ui.activity.PageConnectionHolderFragment$ConnectionHandler$EventHelper.onRetryError(PageConnectionHolderFragment.java:556)
        at com.here.oksse.RealServerSentEvent.retry(RealServerSentEvent.java:105)
        at com.here.oksse.RealServerSentEvent.notifyFailure(RealServerSentEvent.java:98)
        at com.here.oksse.RealServerSentEvent.access$000(RealServerSentEvent.java:26)
        at com.here.oksse.RealServerSentEvent$Reader.read(RealServerSentEvent.java:185)
        at com.here.oksse.RealServerSentEvent.openSse(RealServerSentEvent.java:93)
        at com.here.oksse.RealServerSentEvent.access$100(RealServerSentEvent.java:26)
        at com.here.oksse.RealServerSentEvent$1.onResponse(RealServerSentEvent.java:79)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
````

**Comment by mueller-ma** [comment]
The logging leaks session cookies, e.g. `set-cookie: connect.sid=[REDACTED]; Domain=.myopenhab.org; Path=/; HttpOnly`.

**Comment by maniac103** [comment]
I was wondering whether we should log headers or just the request + response lines. It's easy to redact a particular header though.

**Comment by mueller-ma** [comment]
@maniac103 RTM?

**Comment by maniac103** [comment]
Yes, I think so.

**Pull request merged**
