### PR TITLE
Use yAxisDecimalPattern Chart query parameter

### PR DESCRIPTION
**Pull request by maniac103**
Pretty ugly due to the (very limited) format conversion :-/

### CODE REVIEW

**Comment by mueller-ma** [comment]
Do we need to parse it? I think you can just pass it the query string.

**Comment by maniac103** [comment]
Try it ... I did ;-)
Seriously, no, the formats aren't compatible. For e.g. 2 decimal digits, the state description one (printf-like) is e.g. `%.2f °C`, while the chart one (DecimalFormat) wants `0.00 °C`.

**Comment by J-N-K** [comment]
Exactly. That's because we use XChart and that requires a format string that is compatible with `DecimalFormat`. I see five options here:

1. Write a format-translator in every consumer (like you did)
2. Write a format-translator and integrate it in core (OH4 would be a good candidate for breaking changes)
3. Try to incorporate changes in xchart (IMO not really an option, given that there have been nearly no contributions in the past year and we wait for a 3-line fix to be merges since two month)
4. Fork and use a customized version 
5. Find another library

**Comment by maniac103** [comment]
Option 2 sounds at least better than 1, if possible, since that requires the translation code only once and at the same time improves the OH API.
Given option 3, option 4 might also be an option since there won't be too much effort tracking upstream changes?

**Comment by mueller-ma** [comment]
I prefer option 2 as it avoids writing the same code several times. I think the breaking change shouldn't cause to much issues as the parameter isn't even documented yet: https://next.openhab.org/docs/ui/sitemaps.html#element-type-chart

**Comment by mueller-ma** [comment]
Actually I did try ;)

According to https://github.com/openhab/openhab-core/pull/2937#issuecomment-1114018238 you need to put the pattern in the sitemap that can be read by the chart.

I tried:
* `Chart item=... yAxisDecimalPattern="#"` which make Basic UI to call `https://.../chart?...&yAxisDecimalPattern=%23`
* `Chart item=... yAxisDecimalPattern="#.##E0"` which make Basic UI to call `https://.../chart?...&yAxisDecimalPattern=%23.%23%23E0`

So it seems that the pattern is just passed (and encoded), but Basic UI doesn't convert it in any way.

**Comment by mueller-ma** [comment]
I opened #3274 that just passes this parameter to the chart URL. I'd merge that one as it implements the same behavior than Basic UI.

In the future there could be an enhancement in the chart library or somewhere else on the server to accept printf-like format as well or maybe fallback to the Item state description, if `yAxisDecimalPattern` is absent.

**Comment by maniac103** [comment]
Makes sense. I missed the sitemap parameter part of this.

**Pull request closed without merging**
