### PR TITLE
Clean up MJPEG streaming code.

### PR DESCRIPTION
**Pull request by maniac103**

### CODE REVIEW

**Comment by maniac103** [comment]
This should also fix some subtle bugs, like the streaming not restarting after being interrupted and the stream not being closed.

Can anyone of you guys actually test this?

**Comment by mueller-ma** [comment]
@maniac103 Can you rebase this PR?

**Comment by mueller-ma** [comment]
It's harder to find a mjpeg stream on the internet then I thought and I don't have any webcams.
@lolodomo Do you want to review this PR?

**Comment by maniac103** [comment]
Included in #850

**Pull request closed without merging**
