### PR TITLE
Refine section switch with two mappings

### PR DESCRIPTION
**Pull request by maniac103**
Those should be small enough to fit into one line with label and value.

### CODE REVIEW

**Comment by maniac103** [comment]
Not entirely sure yet whether it's a good idea or inconsistent, but a larger number of users seems to use a double mapping as toggle switch. Open for :+1: :-1:

**Comment by mueller-ma** [comment]
I'd say 👍, but what should we do when the next person comes with: I have a switch with three mappings, but all of them are only one letter?
Add another special case?

**Comment by maniac103** [comment]
> but what should we do when the next person comes with: I have a switch with three mappings, but all of them are only one letter?

That's precisely why I'm torn ;-) But this specific case should be OK, I think, as it's pretty similar to a `Switch` without mappings.

**Comment by alltime84** [comment]
Thanks a lot for implementing! It looks much more consistent now:
image

before:
image

**Pull request merged**
