### PR TITLE
Change value colors according to theme background

### LINKED ISSUE #637: Colors in light theme too bright
When using `valuecolor=[ON="green"]`, basic UI shows a darker green than the app. Even when chaning the basic-ui theme, an intensiv light green (seems `#00FF00') is shown.

This is too bright for a white background.

We should change the colors at least in the basic-ui theme to match the basic ui and provide better accessibility through higher contrast.

Here's a quick comparison between basic UI (first) and app (second)
2018-01-13 08_36_35-technik

img_20180113_084202

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #637

Before:
before1
before2

After:
after1
after2
after3

I'm not sure about both blue and maroon in dark themes. They could be a bit brighter. WDYT?

### CODE REVIEW

**Comment by maniac103** [comment]
> I'm not sure about both blue and maroon in dark themes. They could be a bit brighter. WDYT?
Yes, I agree...same with navy. Yellow and orange also are a little too close to each other for light theme.

**Comment by maniac103** [comment]
@mueller-ma Optimizing the color mapping ... mind cherry-picking https://github.com/maniac103/openhab.android/commit/0b3a149e565c60497e5f977b49545f5eb322ff36 ?

**Comment by mueller-ma** [comment]
@maniac103 Thanks for the optimization.
I made the yellow for bright skins and blue, navy and maroon for dark ones brighter:

screenshot_2018-03-14-16-49-17
screenshot_2018-03-14-16-49-46

**Comment by maniac103** [comment]
@mueller-ma Sure: https://github.com/maniac103/openhab.android/commit/934692768402bf5795f00c9ca4ab10a26433a96f

**Comment by maniac103** [comment]
I've also played with (consistently) using the material design color palette (700 for bright background, accent 400 for dark background):

screenshot_1521103065
screenshot_1521103089

I think it doesn't look too bad? For your consideration: https://github.com/maniac103/openhab.android/commit/ca0233c3ad14620a5863f8952849d4ed2b40b8ed

**Comment by mueller-ma** [comment]
The test with the bright theme is still failing.

**Comment by maniac103** [comment]
Strange, both worked for me when I tested it. I'll check it.
No interest in the color palette change?

**Comment by mueller-ma** [comment]
Maybe it depends on the emulator os.

I missed to comment on your colors, but I want to be as close as possible to the basic ui color sheme.

**Comment by maniac103** [comment]
> The test with the bright theme is still failing.

Fix: https://github.com/maniac103/openhab.android/commit/39533f51dc465347e29369d0417edc533d59488c

**Pull request merged**
