### PR TITLE
Show discrete sliders when only few states are possible

### LINKED ISSUE #1626: Use discrete sliders if only a few states are possible
### Is your feature request related to a problem? Please describe.
By setting minValue, maxValue and/or step it's possible to create sliders, that can only have a few states. It's not visible to the user where the slider will accept the change of the state.
The slider might reject state changes if the new value isn't close to a valid state. The slider will than jump back unexpectedly.

### Describe the solution you'd like
Slider with less than, let's say 10, possible states, should be discrete ones: https://material.io/components/sliders/#discrete-slider

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #1626
Closes #1637

### CODE REVIEW

**Comment by maniac103** [comment]
As mentioned [here](https://github.com/openhab/openhab-android/pull/1623#issuecomment-547110358) I think it would be better to defer this until Material Components 1.2.0 is released, and at that point implement it by switching to their `Slider` class.

**Comment by mueller-ma** [comment]
The new Material Slider uses a new `OnChangeListener` (https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/slider/Slider.java#L205) that has only one callback. The old Slider has a callback that is called, after the slider has been changed. The new Slider callback is called, while dragging the slider. This causes the slider to jump around.

**Comment by maniac103** [comment]
That doesn't seem to be much of a problem though. Just schedule a timeout on change and only run it when things have settled (IOW, reschedule it on every change).

**Comment by mueller-ma** [comment]
> As mentioned here I think it would be better to defer this until Material Components 1.2.0 is released, and at that point implement it by switching to their Slider class.

What about this as an interim solution?

**Comment by maniac103** [comment]
*shrug* Personally I don't see the need for an interim solution, since this is just a cosmetic change.

**Pull request closed without merging**
